### ISSUE TITLE
Mean test not giving correct value the first time run.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/pathway-mapper#17]
Steps to reproduce:
Open any map with genes on rows and some covariates to select groupings from.
Select groupings in the PathwayMapper config dialog that should work when apply selected. (Do not yet hit apply)
Do not select anything on the map.
Instead of looking for a Pathway that matches, just drag some genes over from the toolbar to the pathway and rename them to match something present in the rows of the map.
Run the mean test by clicking apply in the PathwayMapper config dialog.
Note the values.
Click apply a second time.  The values will change.
Subsequent clicking of apply will always stick to the new values.

In one map I tested on that contained gaps, the later, probably correct values were in the same range as the values on the map.
The initial values were huge negative numbers like -10240001 (particular number made up, I didn't copy them down) for which there were no such values in the range of data in the map.

**Comment by marohrdanz** [comment]
To add some additional information: This bug appears to be caused because [getValue in MatrixManager](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/blob/329269a8f20e29ae6e5fd99f651e72a6799dc43c/NGCHM/WebContent/javascript/MatrixManager.js#L1451) returns the down sampled value on the first click of 'APPLY'.

**Comment by marohrdanz** [comment]
Closed by PR in NG-CHM project: https://github.com/MD-Anderson-Bioinformatics/NG-CHM/pull/90
